version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - ./volumes:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    profiles: ["dev", "prod"]

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8001:8001"
    links:
      - db:db
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
    volumes:
      - ".:/app"
      - "/app/cli"
    profiles: ["dev", "prod"]
    networks:
      - default
      - sso

  frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles: ["dev"]

  frontend-prod:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    ports:
      - "3001:3001"
    profiles: ["prod"]

networks:
  sso:
    driver: bridge