from datetime import timedelta

from keys.private import PRIVATE_KEY
from keys.public import PUBLIC_KEY
from sso.settings import DEBUG

API_SETTINGS = {
    # Algorithm.
    # The keys can be generated by following the instructions at
    # https://rietta.com/blog/openssl-generating-rsa-key-from-command/.
    "ALGORITHM": "RS256",
    "PRIVATE_KEY": PRIVATE_KEY,
    "PUBLIC_KEY": PUBLIC_KEY,
    # Cookie.
    "ACCESS_TOKEN_COOKIE_NAME": "jwt_access_token",
    # Life time.
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    # Claims.
    "ISSUER_CLAIM": "sso_server",
    "USER_ID_CLAIM_NAME": "user",
    # Redirect URLs. The allowed audiences are automatically generated from this dict.
    "REDIRECT_URLS": {"rezal": "", "portail": ""},
    "GET_PARAMETER": "access",
}


PROD_MODE = not DEBUG
